from app.models.clinica import Clinica
from app.models.usuario import Usuario
from app.models.especialidad import Especialidad
from app.models.medico import Medico
from app.models.horario import Horario
from app.models.atencion import Atencion
from app.models.triaje import Triaje
from app.models.control_medico import ControlMedico
from app.models.auditoria import Auditoria